name: snap-mart-server # 这里定义的名字会显示在 Docker 面板
# version: '3.8'

services:
  api:
    image: pinkad/snap-mart-api:latest
    container_name: snap-mart-api
    restart: always
    depends_on:
      - db
    environment:
      PORT: 3001
      DATABASE_URL: mysql://root:123456@db:3306/snap_mart
      JWT_SECRET: change_me_to_a_long_random_string
      JWT_EXPIRES_IN: 7d
    ports:
      - "3001:3001"

  db:
    image: mysql:8.0
    container_name: snap-mart-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: snap_mart
    ports:
      - '3308:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
